### ISSUE TITLE
relacs.net broken?

### ISSUE THREAD

**Issue by JuliaSprenger** [relacs/relacs#7]
www.relacs.net does not lead anywhere useful. Is it a broken link or did the project homepage move somewhere else?

**Comment by jgrewe** [comment]
this seems to be a sourceforge issue. "Project web is currently offline pending the final migration of its data to our new datacenter."  (I hope it will be solved soon)
However, please use the version there. The github version is not up-to-date.

**Comment by jgrewe** [comment]
should be resolved. Closing this issue
