### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by pfeffer90** [relacs/relacs#9]
With the current version of the master, the installation fails - >
[make.log](https://github.com/relacs/relacs/files/2514468/make.log). The error seems related to the ephys plugin, which could stem from recent changes, see latest commits.

Any idea why?

It would be great to have a release branch to have a stable version.

**Comment by janscience** [comment]
Hi Paul,

these are the new voltageclamp repros by Lukas.

Simply disable them with

./configure --disable-plugins-voltageclamp

Or pull the latest relacs master brunch, run ./bootstrap.sh and ./configure ,  it is now disabled by default.

Cheers,
Jan
